# Generated by Django 2.2.5 on 2019-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqlins',
            name='isslave',
        ),
        migrations.AddField(
            model_name='mysqlins',
            name='created_by',
            field=models.CharField(choices=[('auto', '自动添加'), ('manual', '手工录入')], default='auto', max_length=32, verbose_name='添加方式'),
        ),
    ]
