# Generated by Django 2.2.5 on 2019-09-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql', '0004_auto_20190930_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlins',
            name='isslave',
            field=models.CharField(choices=[(0, '主库'), (1, '从库')], default=0, max_length=32, verbose_name='是否主从'),
        ),
    ]
