# Generated by Django 2.2.5 on 2019-09-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql', '0005_mysqlins_isslave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlins',
            name='isslave',
            field=models.CharField(choices=[('master', '主库'), ('slave', '从库')], default=0, max_length=32, verbose_name='是否主从'),
        ),
    ]
